# Site settings
title:          Tale
description:    "Mentoring SuperHighway is a free program covering the process of shifting from middle school to high school, which includes talking about grades, choosing rigorous courses, and choosing meaningful extracurriculars."
url:            "https://Mentoring-SuperHighway.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
krish:
    name: Krish Shah
    email: 2003kshah@gmail.com
guest: 
    name: Guest Person

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       2

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
